version: '3.8'

services:
  mysql:
    image: mysql:8.0-oracle
    container_name: mysql_java
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  mysql_data: